# .github/workflows/<some name>.yaml
name: Build, Test and Publish

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
    
env: # This is the environment variables section Global variables
  TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
  

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Tag with Release Version
        run: |
          git tag some_tag
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m pip install twine
          python -m pip install pre-commit
      - name: Install other dependencies
        run: |
          /bin/bash -x run.sh install
      - name: Lint the code for pre-commit
        run: |
            /bin/bash -x run.sh lint:ci
      - name: Build the package
        run: |
          /bin/bash -x run.sh build

        #post merge
      - name: Publish to TestPyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          /bin/bash -x run.sh publish:test
        env:
            TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }} #github expression
      - name: Publish to ProdPyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          /bin/bash -x run.sh publish:prod
        env:
            TEST_PYPI_PASSWORD: ${{ secrets.PROD_PYPI_PASSWORD }} #github expression
      - name: Push tags
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
              git push origin --tags

  # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-printing-context-information-to-the-log
  # dump_contexts_to_log:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"
  #     - name: Dump job context
  #       env:
  #         JOB_CONTEXT: ${{ toJson(job) }}
  #       run: echo "$JOB_CONTEXT"
  #     - name: Dump steps context
  #       env:
  #         STEPS_CONTEXT: ${{ toJson(steps) }}
  #       run: echo "$STEPS_CONTEXT"
  #     - name: Dump runner context
  #       env:
  #         RUNNER_CONTEXT: ${{ toJson(runner) }}
  #       run: echo "$RUNNER_CONTEXT"
  #     - name: Dump strategy context
  #       env:
  #         STRATEGY_CONTEXT: ${{ toJson(strategy) }}
  #       run: echo "$STRATEGY_CONTEXT"
  #     - name: Dump matrix context
  #       env:
  #         MATRIX_CONTEXT: ${{ toJson(matrix) }}
  #       run: echo "$MATRIX_CONTEXT"
  #     - name: Dump secrets context
  #       env:
  #         SECRETS_CONTEXT: ${{ toJson(secrets) }}
  #       run: echo "$SECRETS_CONTEXT"
  #     - name: Dump runner context
  #       env:
  #         VARS_CONTEXT: ${{ toJson(vars) }}
  #       run: echo "$VARS_CONTEXT"
        
        
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: 3.8
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pre-commit
  #     - name: Analysing the code with pylint
  #       run: |
  #         SKIP=no-commit-to-branch pre-commit run --all-files
